class "struct work" as s_work {
   cb
   cb_data
   timeout
   flags
}
hide s_work methods

enum flags {
   SYNC
   ASYNC
}
hide flags methods

class "struct work_queue_timesource" as s_wq_timesource
hide s_wq_timesource methods
hide s_wq_timesource attributes

class "work_queue" as wq {
   + work_schedule()
   + work_reschedule()
   + work_cancel()
   - is_work_pending()
   - work_next_timeout()
   - run_work()
   - work : list
}

class client #a1a1ca
hide client methods
hide client attributes

wq o- s_work
wq <- s_wq_timesource : provides timer INT

s_work - flags

client -> s_work : (1) creates
client ---> wq : (2) schedules work
wq ---> client : (3) calls cb(cb_data) upon timeout
