
package audio {
    component "<comp>" as comp
}

interface dma_get
component "lib::\ndma" as lib_dma

lib_dma -up- dma_get

interface dma_ops

component "drivers::dma::\n<dma impl>" as dma_impl
dma_impl -up- dma_ops

component "platform" as plat

lib_dma <. dma_impl : (1) registered\nby platform

dma_ops <. plat : (2) calls probe() @init

comp ..> dma_get : (3) obtains dmac
comp ..> dma_ops : (4) calls API
