@startuml

participant "DMIC Manager" as dmic_manager
participant "Zephyr PM Subsystem" as zephyr_pm
participant "DMIC Driver" as dmic_driver

-> dmic_manager : gateway_allocate()
	activate dmic_manager
	dmic_manager -> zephyr_pm : pm_runtime_device_get (dmic)

		activate zephyr_pm
		zephyr_pm -> zephyr_pm : increase usage count
		opt if usage == 1
		zephyr_pm -> dmic_driver : pm_device_resume
			activate dmic_driver
			return
		end
		return

	deactivate dmic_manager
<-- dmic_manager

@enduml
