participant "pipeline" as ppl
participant "component" as comp

-> ppl : pipeline_task()
   activate ppl
   ppl -> ppl : pipeline_copy_from_upstream()
      activate ppl
      ppl -> comp : comp_copy()
   ppl <-- ppl
   deactivate ppl
   ppl -> ppl : pipeline_copy_to_downstream()
      activate ppl
      ppl -> comp : comp_copy()
   ppl <-- ppl
   deactivate ppl
<-- ppl
deactivate ppl
