participant "State" as st
participant "Error" as err
participant "Host\nDriver" as host
participant "APL\nROM" as rom
participant "CSE" as cse

host -> rom : <<IPC>> RomControl (purge=1, dma_id)

== Initialization ==
rom -> rom : Boot
	err <[#red]- rom : ADSP_UNHANDLED_INTERRUPT [anytime unhandled int reported]
	err <[#red]- rom : ADSP_MEMORY_HOLE_ECC [anytime memory hole int reported]
	err <[#red]- rom : ADSP_USER_EXCEPTION [anytime unhandled user mode exception happens]
	err <[#red]- rom : ADSP_KERNEL_EXCEPTION [anytime unhandled kernel mode exception happens]

rom -> rom : L2Cache Initialization
	err <[#red]- rom : ADSP_L2_CACHE_ERROR [Failed to init L2$]

rom -> rom : Requesting IMR
	st <[#green]- rom : FSR_ROM_BASEFW_CSE_IMR_REQUEST
	rom -> cse : <<IPC>> IPC_ADSP2CSE_REQUEST_IMR
	rom <- cse : <<IPC>> IPC_CSE2ADSP_REQUEST_IMR_RESPONSE
	st <[#green]- rom : FSR_ROM_BASEFW_CSE_IMR_GRANTED

rom -> rom : Initializing Code Load DMA
	err <[#red]- rom : ADSP_INVALID_PARAM [dma_id out of range]

st <[#green]- rom : FSR_ROM_INIT_DONE

== Loading Image ==
	rom -> rom : Loading Firmware
	' First fw image block is loaded and feature mask is verified
	st <[#green]- rom : FSR_ROM_VERIFY_FEATURE_MASK
	err <[#red]- rom : ADSP_INVALID_FEAT_MASK [mft mask does not match SKUID]
	' Load offset is verified
	st <[#green]- rom : FSR_ROM_GET_LOAD_OFFSET
	err <[#red]- rom : ADSP_LOAD_OFFSET_TOO_SMALL [load offset less then Rsvd space]
	err <[#red]- rom : ADSP_IMR_TOO_SMALL [load offset greater than assigned IMR size]
	' CSE Manifest if loaded
	rom -> rom : Loading CSE Manifest
	err <[#red]- rom : ADSP_IMR_TOO_SMALL [CSE manifest > IMR size]
	st <[#green]- rom : FSR_ROM_CSE_MANIFEST_LOADED
	' FW Manifest is loaded
	rom -> rom : Loading ADSP FW Manifest
	err <[#red]- rom : ADSP_IMR_TOO_SMALL [ADSP FW manifest > IMR size]
	st <[#green]- rom : FSR_ROM_FW_MANIFEST_LOADED
	err <[#red]- rom : ADSP_BASE_FW_NOT_FOUND [module entry not found in manifest]
	' Loading rest of FW
	rom -> rom : Loading FW
	st <[#green]- rom : FSR_ROM_FW_FW_LOADED

== Authenticating Image ==
	st <[#green]- rom : FSR_ROM_BASEFW_CSE_VALIDATE_IMAGE_REQUEST
	rom -> cse : <<IPC>> IPC_CSE2ADSP_START_FW_AUTH
	rom <- cse : <<IPC>> IPC_CSE2ADSP_START_FW_AUTH_RESPONSE
	err <[#red]- rom : ADSP_CSE_VALIDATION_FAILED [invalid image signature]
	st <[#green]- rom : FSR_ROM_BASEFW_CSE_IMAGE_VALIDATED
== Booting FW ==
	st <[#green]- rom : FSR_ROM_FW_ENTERED
