actor host as "Host"
participant cldma as "CodeLoadDMA"

activate host
host -> host : read(): binary
host -> host : detect and strip Extended Manifest : binary_mft_code
host -> host : retrieve preload size (binary_mft_code) : preload_size

host -> cldma : write (binary_mft_code, mft_size)
host -> cldma : write (binary_mft_code+mft_size, preload_size-mft_size)
