hide empty description
[*] -right-> COMP_STATE_INIT : start of <b>comp_ops.new()</b>

COMP_STATE_INIT --> COMP_STATE_READY : end of <b>comp_ops.new()</b>

COMP_STATE_READY ---> COMP_STATE_PREPARE : <b>COMP_TRIGGER_PREPARE</b>

COMP_STATE_PREPARE --> COMP_STATE_ACTIVE : <b>COMP_TRIGGER_START</b>

COMP_STATE_ACTIVE --> COMP_STATE_PREPARE : COMP_TRIGGER_STOP
COMP_STATE_PAUSED --> COMP_STATE_PREPARE : COMP_TRIGGER_STOP

COMP_STATE_ACTIVE -> COMP_STATE_PAUSED : COMP_TRIGGER_PAUSE

COMP_STATE_PAUSED --> COMP_STATE_ACTIVE : COMP_TRIGGER_RELEASE

COMP_STATE_PREPARE --> COMP_STATE_READY : COMP_TRIGGER_RESET
